spring.application.name=crudapp

#database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#app setting

#off banner warning
spring.main.banner-mode=off 
logging.level.root=off

##display only info
#logging.level.root=info
#
##display only warning
#logging.level.root=warn

#Database setting -> specify properties entity to table

# update = if have change in entity class, it will change table too
spring.jpa.hibernate.ddl-auto=update 
